export const SCREEN_NAME = {
  CHANGE_PASSWORD: 'CHANGE_PASSWORD_SCREEN',
  ORDER: 'ORDER_SCREEN',
  NOTIFICATION: 'NOTIFICATION_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
  TRANSACTION: 'TRANSACTION_SCREEN',
  HOME: 'HOME_SCREEN',
  LOGIN: 'LOGIN_SCREEN',
  MAIN: 'MAIN_SCREEN'
}